### ISSUE TITLE
How to save created graph?

### ISSUE THREAD

**Issue by Danil-Kutnyy** [furechan/mplchart#1]
Hi guys! Thank you for this awesome software, I use it in my little telegram project. 

However, I faced one issue, I can not save created chart automatically. `.show()` method works fine and allow to show and save created chart, but `.savefig` method doesn't work. So the only way I can save chart is to show it and then save manually with grapthic interface. I wonder if I'm just dumb, or there is really no way to save created chart? 

Thanks for awesome code anyway!

**Comment by furechan** [comment]
You can use save savefig on the figure attribute : chart.figure.savefig(...)

**Comment by Danil-Kutnyy** [comment]
Thank you, it works
