### ISSUE TITLE
linestyle,linewidth,linecolor as arguments in indicators function calls

### ISSUE THREAD

**Issue by vinaychuri** [furechan/mplchart#12]
The following code allows users to plot the candlestick and the required TA indicators. Is there any option to pass "linestyle,linewidth,linecolor" as arguments to the indicator functions?

```
indicators = [
        Candlesticks(), EMA(9), EMA(21), Volume(),RSI()
    ]
    chart = Chart()
    chart.plot(plot_df, indicators)
```

As of now I had to edit the functions to format the  plot lines to suit my requirements but making the above request in case its possible.

THANKS!! for an excellent plotting package 👍

**Comment by furechan** [comment]
Hi @vinaychuri,

There is currently no easy way to parametrize the styling of indicators. I am looking to add such capability in a future version ...

**Comment by vinaychuri** [comment]
Understood

**Comment by furechan** [comment]
Hi @vinaychuri,

Letting your know that, the latest version of `mplchart` includes a `LinePlot` primitive that allows you to customize the styling of an indicator.

Syntax is like:

```python
SMA(50) | LinePlot(style=..., color=..., width=...)
```
