### ISSUE TITLE
Volume colours

### ISSUE THREAD

**Issue by pajones007** [furechan/mplchart#2]
Hi Furechan -- you may want to check your 'colours' for indicating volume when price moves higher (green), a price moves lower (red) or remains neutral price open/close (grey?).  I think this has been inversed as I checked against other charts, those charts indicate green volumes, MPLCharts is red volume.  Love what youv'e accomplished

**Comment by furechan** [comment]
Hi, the volume colors have been fixed in latest commit... Thank you

**Comment by pajones007** [comment]
Great thanks for the update...
