### ISSUE TITLE
Creating chart arrays

### ISSUE THREAD

**Issue by Ajith-82** [furechan/mplchart#3]
Hi,

Thank you for the excellent plotting module. While I’ve successfully used it to plot technical indicators for individual stocks, I’m struggling to figure out how to create multiple stock charts in a single plot. Currently, my workaround involves saving individual charts as images and then stitching them together into a single image. Is there a more efficient solution you could recommend?

Thanks,
Ajith

**Comment by Ajith-82** [comment]
Hi,

Thank you for the update.

**Comment by furechan** [comment]
Hi Ajith,

I looked into this a little further. The latest release adds a way to plot multiple assets in the same chart. This is a tentative solution.

```
chart = Chart(title="Versus", max_bars=max_bars, style=style)
chart.plot(data1, [ Candlesticks(), Volume(), RSI(), MACD() ] )
chart.plot(data2, [ Price() ] , target='main')
```

You can add replace=True in the second plot to have the prices rebased to the first series.

Example in examples/multiple-plots.ipynb

**Comment by Ajith-82** [comment]
Hi,

Thank you very much. I really appreciate your help.

**Comment by furechan** [comment]
Glad it was helpful.
