### ISSUE TITLE
chart.plot isn't plotting

### ISSUE THREAD

**Issue by eldargoren** [furechan/mplchart#6]
Hi, this project looks amazing.
I couldn't print the chart for some reason so I just copied the demo but it didn't do anything,
Any Idea why?

![image](https://github.com/furechan/mplchart/assets/71339152/9d2f071e-7977-4c61-aab4-1475bcd178ed)

I do have data in prices dataframe.

**Comment by furechan** [comment]
Hi @eldargoren,

The example in the README is meant to be run from a notebook cell. When running from a script you have to call `chart.show()` or alternatively `plt.show()` after `chart.plot(...)`. See `chart-from-script.py` in the examples folder. I will try and clarify the README ...

**Comment by eldargoren** [comment]
Thanks!
But it’s pretty weird because I ran it in a notebook cell. I Will try soon your suggestion.

**Comment by eldargoren** [comment]
@furechan 
Also nothing :(
![image](https://github.com/furechan/mplchart/assets/71339152/2cfc20fd-e9c1-4679-9208-26d2ec7ff792)

**Comment by furechan** [comment]
Hi,

Not sure what is going on. Maybe you have a custom notebook/matplotlib configuration ?

Few things to try:

1) Check Matplotlib backend

```python
import matplotlib as mpl
mpl.get_backend()
```

2) Try matplotlib inline if not already configured inline

```python
%matplotlib inline
```

3) Try an empty plot to make sure matplotlib works

```python
import matplotlib.pyplot as plt
plt.plot()
plt.show()
```

Hope this helps ...

**Comment by eldargoren** [comment]
You're a genius!
Probably an import of something of matplotlib screwed this up, idk which one.
The graphs are truly amazing.
Thanks!
