### ISSUE TITLE
Custom plot colors and missing x axis time labels

### ISSUE THREAD

**Issue by neodawn** [furechan/mplchart#8]
I have a few queries:

1) Is there a way to set a specific color to each plot line? I would like to set specific color as I have a number of them.
2) I am trying to plot a 3 minute candles, but the time is not visible in the x-axis. Is there a way to enable them?
3) How to set the color of the candles to red and green instead of black and white?

![mplchart_01](https://github.com/furechan/mplchart/assets/2855934/cd82cc34-72ae-40d3-a5b6-bcba45e8f4a8)

Data:
```
date,open,high,low,close,volume
2024-05-13 09:15:00,1423.65,1423.65,1417.0,1418.7,145165
2024-05-13 09:18:00,1419.0,1419.05,1416.4,1418.8,67408
2024-05-13 09:21:00,1418.5,1419.9,1417.45,1419.35,54811
2024-05-13 09:24:00,1419.05,1420.3,1418.7,1419.0,43628
2024-05-13 09:27:00,1419.0,1419.9,1417.95,1418.85,77544
2024-05-13 09:30:00,1418.5,1418.65,1415.65,1415.65,56645
2024-05-13 09:33:00,1415.75,1416.95,1415.1,1415.95,37163
2024-05-13 09:36:00,1415.9,1416.4,1414.4,1414.75,37488
```

Code Snippet:
```
    with plot:
        chart = Chart(title=ticker.value, max_bars=max_bars, figure=plot.fig)
        chart.plot(df, indicators)
        chart.plot(df, [Price(item="l_high_plot")], target="main")
        chart.plot(df, [Price(item="l_low_plot")], target="main")
        chart.plot(df, [Price(item="final_u_plot")], target="main")
        chart.plot(df, [Price(item="final_l_plot")], target="main")
        chart.plot(df, [Price(item="ema20")], target="main")
        chart.plot(df, [Price(item="ema25")], target="main")
        chart.plot(df, [Price(item="ema30")], target="main")
        chart.plot(df, [Price(item="ema100")], target="main")
        chart.plot(df, [Price(item="ema200")], target="main")        

        chart.plot(df, [Price(item="count")], target="below")  
        
        ui.update(plot)
```

**Comment by furechan** [comment]
Hi @neodawn,

1) There is no easy way to customize colors at this stage. You my try to play with the matplotlib color cycler, but this is a very indirect way
2) I will try and add handling of minutes ticks ...
3) No easy way to style the candles at this stage

If you are plotting data line by line, you may want to have a look at
[mplfinance](https://github.com/matplotlib/mplfinance),
it is a mature project with lots of customizations.

**Comment by neodawn** [comment]
ok. Thanks for the inputs.
