### ISSUE TITLE
How can I plot a singular point?

### ISSUE THREAD

**Issue by syntaxsdev** [furechan/mplchart#9]
I've tried many ways to plot a singular point with what `Chart` module returns, such as Custom Indicators with NaN's for everything else, accessing the axes, I can't get it to show, it defaults any singular Series point with values of NaN to a legend only.

**Comment by furechan** [comment]
Hi @syntaxsdev,

I am not sure what you are trying to achieve here. In anycase, you can always access the matplotlib figure as `chart.figure` but the module translates dates to positions so it would be difficult for you to add graphics without knowing the internals of the library...

**Comment by syntaxsdev** [comment]
Hi, @furechan, I was able to do it by directly modifying the chart.py to include a plot_points method. It allows you to plot singular points and labels (for example if you wanted to add a dot and an arrow to show where a specific indication is).  If you are okay with that, I can submit a PR on it and we can adjust to your liking.

**Comment by syntaxsdev** [comment]
Ok - no problem. I will keep the fork open as I am probably going to add more eventually.
